# Generated by Django 3.0.5 on 2020-04-29 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headed_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='explorer.Instructor')),
                ('name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='explorer.Department')),
            ],
        ),
    ]
