# Generated by Django 3.0.5 on 2020-04-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0002_departmenthead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='teaches',
        ),
        migrations.AddField(
            model_name='instructor',
            name='teaches',
            field=models.ManyToManyField(to='explorer.Course'),
        ),
    ]
