# Generated by Django 3.0.5 on 2020-04-29 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0003_auto_20200428_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='teaches',
        ),
        migrations.AddField(
            model_name='course',
            name='taught_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='explorer.Instructor'),
        ),
    ]
